#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    fib = []
    n = int(input().strip())
    a,b = 0,1
    while b<n:
        a, b = b, a + b
        if b<n and b%2==0:
            fib.append(b)
    print (sum(fib))
