#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    total = 0
    n = int(input().strip())
    three = (n-1)//3
    five = (n-1)//5
    fifteen = (n-1)//15
    total += 3*(three*(three+1)//2)
    total += 5*(five*(five+1)//2)
    total -= 15*(fifteen*(fifteen+1)//2)
    print (int(total))
