#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    factors = []
    d =2
    while n>1:
        while n%d==0:
            factors.append(d)
            n /= d
        d += 1
        if d*d>n:
            if n>1:
                factors.append(n)
            break
      
    largestPrimeFactor = max(factors)
    print (int(largestPrimeFactor))
    
