#! /bin/bash
# given three side lengths of a triangle on each line
# find the type of triangle

read x
read y
read z
if(($x == $y && $y == $z));
then
    echo EQUILATERAL
elif(($x == $y || $y == $z || $x == $z));
then
    echo ISOSCELES
else
    echo SCALENE
fi
